/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author julzo
 */
public class DevinQuiz extends javax.swing.JFrame {
    //Variable Delcaration Area
    int answer1;
    final int ANSWER1FINAL = 3;
    final String CHECKMARK = "\u2713";
    final String INCORRECT = "X";
    
    int answer2;
    final int ANSWER2FINAL = 2;
    
    int answer3;
    final int ANSWER3FINAL = 3;
    
    int answer4;
    final int ANSWER4FINAL = 1;
    
     int answer5;
     final int ANSWER5FINAL = 2;
     
     int totalCorrect = 0;
     int totalIncorrect = 0;
     double totalCorrectPercentage;
     
            
    /**
     * Creates new form DevinQuiz
     */
    public DevinQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Q1Title = new javax.swing.JLabel();
        Instruction_lbl = new javax.swing.JLabel();
        Question1_lbl = new javax.swing.JLabel();
        Blue_lbl = new javax.swing.JLabel();
        Red_lbl = new javax.swing.JLabel();
        Yellow_lbl = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Answer1_txt = new javax.swing.JTextField();
        Correction1_txt = new javax.swing.JTextField();
        Q1Title1 = new javax.swing.JLabel();
        Instruction_lbl1 = new javax.swing.JLabel();
        Question1_lbl1 = new javax.swing.JLabel();
        Blue_lbl1 = new javax.swing.JLabel();
        Red_lbl1 = new javax.swing.JLabel();
        Yellow_lbl1 = new javax.swing.JLabel();
        Answer1_txt1 = new javax.swing.JTextField();
        Correction1_txt1 = new javax.swing.JTextField();
        Answer1_txt2 = new javax.swing.JTextField();
        Correction1_txt2 = new javax.swing.JTextField();
        Q1Title2 = new javax.swing.JLabel();
        Instruction_lbl2 = new javax.swing.JLabel();
        Question1_lbl2 = new javax.swing.JLabel();
        Blue_lbl2 = new javax.swing.JLabel();
        Red_lbl2 = new javax.swing.JLabel();
        Yellow_lbl2 = new javax.swing.JLabel();
        Answer1_txt3 = new javax.swing.JTextField();
        Correction1_txt3 = new javax.swing.JTextField();
        Q1Title3 = new javax.swing.JLabel();
        Instruction_lbl3 = new javax.swing.JLabel();
        Question1_lbl4 = new javax.swing.JLabel();
        Blue_lbl3 = new javax.swing.JLabel();
        Red_lbl3 = new javax.swing.JLabel();
        Yellow_lbl3 = new javax.swing.JLabel();
        Q1Title4 = new javax.swing.JLabel();
        Instruction_lbl4 = new javax.swing.JLabel();
        Question1_lbl5 = new javax.swing.JLabel();
        Blue_lbl4 = new javax.swing.JLabel();
        Red_lbl4 = new javax.swing.JLabel();
        Yellow_lbl4 = new javax.swing.JLabel();
        Answer1_txt4 = new javax.swing.JTextField();
        Correction1_txt4 = new javax.swing.JTextField();
        Correct_lbl = new javax.swing.JLabel();
        Correct_txt = new javax.swing.JTextField();
        Incorrect_lbl = new javax.swing.JLabel();
        Incorrect_txt1 = new javax.swing.JTextField();
        Percentage_lbl = new javax.swing.JLabel();
        Percentage_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Q1Title.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Q1Title.setText("Question 1");

        Instruction_lbl.setText("Type the number in the box");

        Question1_lbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Question1_lbl.setText("What is the colour of a banana?");

        Blue_lbl.setText("1. Blue");

        Red_lbl.setText("2. Purple");

        Yellow_lbl.setText("3. Yellow");

        Submit.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Answer1_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer1_txtActionPerformed(evt);
            }
        });

        Q1Title1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Q1Title1.setText("Question 2");

        Instruction_lbl1.setText("Type the number in the box");

        Question1_lbl1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Question1_lbl1.setText("What is the colour of an apple?");

        Blue_lbl1.setText("1. Blue");

        Red_lbl1.setText("2. Red/Green");

        Yellow_lbl1.setText("3. Orange");

        Answer1_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer1_txt1ActionPerformed(evt);
            }
        });

        Answer1_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer1_txt2ActionPerformed(evt);
            }
        });

        Q1Title2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Q1Title2.setText("Question 3");

        Instruction_lbl2.setText("Type the number in the box");

        Question1_lbl2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Question1_lbl2.setText("What is the colour of a Pear?");

        Blue_lbl2.setText("1. Blue/Purple");

        Red_lbl2.setText("2. Red/Orange");

        Yellow_lbl2.setText("3. Yellow/Green");

        Answer1_txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer1_txt3ActionPerformed(evt);
            }
        });

        Q1Title3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Q1Title3.setText("Question 4");

        Instruction_lbl3.setText("Type the number in the box");

        Question1_lbl4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Question1_lbl4.setText("What is the colour of a Birch tree?");

        Blue_lbl3.setText("1. White and black");

        Red_lbl3.setText("2. Brown");

        Yellow_lbl3.setText("3. Black");

        Q1Title4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Q1Title4.setText("Question 5");

        Instruction_lbl4.setText("Type the number in the box");

        Question1_lbl5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Question1_lbl5.setText("What is the colour of a Shiny Gyarados?");

        Blue_lbl4.setText("1. Blue and Black");

        Red_lbl4.setText("2. Red");

        Yellow_lbl4.setText("3. Gray and Red");

        Answer1_txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer1_txt4ActionPerformed(evt);
            }
        });

        Correct_lbl.setText("Total Correct:");

        Incorrect_lbl.setText("Total Incorrect:");

        Percentage_lbl.setText("Percentage Earned:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Answer1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Correction1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Yellow_lbl)
                                    .addComponent(Red_lbl)
                                    .addComponent(Blue_lbl)
                                    .addComponent(Question1_lbl)
                                    .addComponent(Instruction_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Q1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Answer1_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Correction1_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Yellow_lbl1)
                                    .addComponent(Red_lbl1)
                                    .addComponent(Blue_lbl1)
                                    .addComponent(Question1_lbl1)
                                    .addComponent(Instruction_lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Q1Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Correct_lbl)
                                .addGap(162, 162, 162))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Answer1_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Correction1_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Yellow_lbl2)
                                                    .addComponent(Question1_lbl2)
                                                    .addComponent(Instruction_lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Q1Title2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(Blue_lbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Red_lbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Yellow_lbl3)
                                                    .addComponent(Red_lbl3)
                                                    .addComponent(Blue_lbl3)
                                                    .addComponent(Question1_lbl4)
                                                    .addComponent(Instruction_lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Q1Title3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(Answer1_txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Correction1_txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Answer1_txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Correction1_txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Yellow_lbl4)
                                            .addComponent(Red_lbl4)
                                            .addComponent(Blue_lbl4)
                                            .addComponent(Question1_lbl5)
                                            .addComponent(Instruction_lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Q1Title4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(73, 73, 73)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Incorrect_lbl)
                                                    .addComponent(Percentage_lbl))
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Percentage_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Incorrect_txt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Correct_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(112, 112, 112)
                                                .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(0, 39, Short.MAX_VALUE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Q1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Instruction_lbl)
                                .addGap(18, 18, 18)
                                .addComponent(Question1_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Blue_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Red_lbl)
                                .addGap(18, 18, 18)
                                .addComponent(Yellow_lbl)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Correction1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Answer1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Q1Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Instruction_lbl1)
                                .addGap(18, 18, 18)
                                .addComponent(Question1_lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Blue_lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Red_lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Yellow_lbl1)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Correction1_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Answer1_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addComponent(Q1Title2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Instruction_lbl2)
                        .addGap(18, 18, 18)
                        .addComponent(Question1_lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Blue_lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Red_lbl2)
                        .addGap(18, 18, 18)
                        .addComponent(Yellow_lbl2)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Correction1_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Answer1_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Q1Title3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Instruction_lbl3)
                        .addGap(18, 18, 18)
                        .addComponent(Question1_lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Blue_lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Red_lbl3)
                        .addGap(18, 18, 18)
                        .addComponent(Yellow_lbl3)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Correction1_txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Answer1_txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Q1Title4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(Instruction_lbl4))
                    .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Question1_lbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Blue_lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Red_lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Yellow_lbl4)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Correction1_txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Answer1_txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Correct_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correct_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Incorrect_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Incorrect_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Percentage_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Percentage_lbl))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        answer1 =Integer.parseInt(Answer1_txt.getText());
        
        if (answer1 == ANSWER1FINAL){
         Correction1_txt.setText(CHECKMARK);   
        }else{
         Correction1_txt.setText(INCORRECT);
        }
        
        
         answer2 =Integer.parseInt(Answer1_txt1.getText());
        
        if (answer2 == ANSWER2FINAL){
         Correction1_txt1.setText(CHECKMARK);   
        }else{
         Correction1_txt1.setText(INCORRECT);
        }
        
         answer3 =Integer.parseInt(Answer1_txt2.getText());
        
        if (answer3 == ANSWER3FINAL){
         Correction1_txt2.setText(CHECKMARK);   
        }else{
         Correction1_txt2.setText(INCORRECT);
        }
        
         answer4 =Integer.parseInt(Answer1_txt3.getText());
        
        if (answer4 == ANSWER4FINAL){
         Correction1_txt3.setText(CHECKMARK);   
        }else{
         Correction1_txt3.setText(INCORRECT);
        }
        
         answer5 =Integer.parseInt(Answer1_txt4.getText());
        
        if (answer5 == ANSWER5FINAL){
         Correction1_txt4.setText(CHECKMARK);   
        }else{
         Correction1_txt4.setText(INCORRECT);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void Answer1_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Answer1_txtActionPerformed

    private void Answer1_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer1_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Answer1_txt1ActionPerformed

    private void Answer1_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer1_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Answer1_txt2ActionPerformed

    private void Answer1_txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer1_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Answer1_txt3ActionPerformed

    private void Answer1_txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer1_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Answer1_txt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevinQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevinQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevinQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevinQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevinQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer1_txt;
    private javax.swing.JTextField Answer1_txt1;
    private javax.swing.JTextField Answer1_txt2;
    private javax.swing.JTextField Answer1_txt3;
    private javax.swing.JTextField Answer1_txt4;
    private javax.swing.JLabel Blue_lbl;
    private javax.swing.JLabel Blue_lbl1;
    private javax.swing.JLabel Blue_lbl2;
    private javax.swing.JLabel Blue_lbl3;
    private javax.swing.JLabel Blue_lbl4;
    private javax.swing.JLabel Correct_lbl;
    private javax.swing.JTextField Correct_txt;
    private javax.swing.JTextField Correction1_txt;
    private javax.swing.JTextField Correction1_txt1;
    private javax.swing.JTextField Correction1_txt2;
    private javax.swing.JTextField Correction1_txt3;
    private javax.swing.JTextField Correction1_txt4;
    private javax.swing.JLabel Incorrect_lbl;
    private javax.swing.JTextField Incorrect_txt1;
    private javax.swing.JLabel Instruction_lbl;
    private javax.swing.JLabel Instruction_lbl1;
    private javax.swing.JLabel Instruction_lbl2;
    private javax.swing.JLabel Instruction_lbl3;
    private javax.swing.JLabel Instruction_lbl4;
    private javax.swing.JLabel Percentage_lbl;
    private javax.swing.JTextField Percentage_txt;
    private javax.swing.JLabel Q1Title;
    private javax.swing.JLabel Q1Title1;
    private javax.swing.JLabel Q1Title2;
    private javax.swing.JLabel Q1Title3;
    private javax.swing.JLabel Q1Title4;
    private javax.swing.JLabel Question1_lbl;
    private javax.swing.JLabel Question1_lbl1;
    private javax.swing.JLabel Question1_lbl2;
    private javax.swing.JLabel Question1_lbl4;
    private javax.swing.JLabel Question1_lbl5;
    private javax.swing.JLabel Red_lbl;
    private javax.swing.JLabel Red_lbl1;
    private javax.swing.JLabel Red_lbl2;
    private javax.swing.JLabel Red_lbl3;
    private javax.swing.JLabel Red_lbl4;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Yellow_lbl;
    private javax.swing.JLabel Yellow_lbl1;
    private javax.swing.JLabel Yellow_lbl2;
    private javax.swing.JLabel Yellow_lbl3;
    private javax.swing.JLabel Yellow_lbl4;
    // End of variables declaration//GEN-END:variables
}
